[build]
command = "cd main && python manage.py collectstatic --noinput"
publish = "/"


 [build]
command = "cd d:/programs/programs/learning_log/learning_log && python manage.py collectstatic --noinput"
publish = "/"


[build]
command = "cd d:/programs/programs/learning_log/learning_log && python manage.py collectstatic --noinput"
publish = "/"





