# Generated by Django 4.1.7 on 2023-05-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
    ]
